version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    labels:
      - dependabot

  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    schedule:
      interval: weekly
    labels:
      - dependabot
