name: release
on: 
  push:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      BUILD_DIR: ${{ steps.build_dir.outputs.BUILD_DIR }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      
      - name: Build project assets
        id: build_dir
        run: |
          npm run build:prod
          echo "::set-output name=BUILD_DIR::$(pwd)/public"

  deployDev:
    needs: build
    runs-on: ubuntu-latest
    environment: deployDev
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Configure AWS Dev credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync Built Assets To S3
        run: aws s3 sync ${{ needs.build.outputs.BUILD_DIR }} s3://${{ secrets.AWS_DEST_BUCKET }} --cache-control "max-age=86400" --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths '/*'

  deployProd:
    needs: build
    runs-on: ubuntu-latest
    environment: deployProd
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Configure AWS Prod credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync Built Assets To S3 
        run: aws s3 sync ${{ needs.build.outputs.BUILD_DIR }} s3://${{ secrets.AWS_DEST_BUCKET }} --cache-control "max-age=86400" --delete

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID }} --paths '/*'

      - name: Semantic Release
        run: |
          export GH_TOKEN=${{ github.token }}
          npm run zip:assets
          npx semantic-release
